
title: My Resume
url: 'https://zhouzang.github.io/'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Zhou Zang  ## put your name
title: 'Graduating Student from Beijing Normal University'  ## your title
location: Beijing , China



# Update all the sections by editing the files inside _includes folder.
